name: door_security_lock_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  get: ^4.6.5
  google_fonts: ^4.0.1
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  modern_form_line_awesome_icons: ^2.0.1
  cloud_firestore: ^4.9.1
  awesome_snackbar_content: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#F7F6F1"
  color_dark: "#272727"
  image: assets/images/welcome_images/welcome_screen_image.jpg
  image_dark: assets/images/welcome_images/welcome_screen_image.jpg

android_12:
  image: assets/images/welcome_images/welcome_screen_image.jpg
  icon_background_color: "#F7F6F1"
  image_dark: assets/images/welcome_images/welcome_screen_image.jpg
  icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/dashboard/
    - assets/images/profile/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
