// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUfL2TotSgH5785aAX6upMeV8iM9Fhi8',
    appId: '1:859862233087:web:b118bcbd7f9aca56fa81ca',
    messagingSenderId: '859862233087',
    projectId: 'door-security-lock-app',
    authDomain: 'door-security-lock-app.firebaseapp.com',
    storageBucket: 'door-security-lock-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3ITU8UIoQX_ruHeZAxmvyi3GlLkhD7k',
    appId: '1:859862233087:android:7464660776e5b37bfa81ca',
    messagingSenderId: '859862233087',
    projectId: 'door-security-lock-app',
    storageBucket: 'door-security-lock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rcGgmMXCpka_u8_NIjPJ8V8cXPDr1ag',
    appId: '1:859862233087:ios:ca63bc7d4546766efa81ca',
    messagingSenderId: '859862233087',
    projectId: 'door-security-lock-app',
    storageBucket: 'door-security-lock-app.appspot.com',
    androidClientId: '859862233087-qdagj10ar0mhv1i2ofljns6ilkq15r8o.apps.googleusercontent.com',
    iosClientId: '859862233087-fiv9en2dg3cir5e4dfeflmptdhcc1dom.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorSecurityLockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rcGgmMXCpka_u8_NIjPJ8V8cXPDr1ag',
    appId: '1:859862233087:ios:887056783aa65b28fa81ca',
    messagingSenderId: '859862233087',
    projectId: 'door-security-lock-app',
    storageBucket: 'door-security-lock-app.appspot.com',
    androidClientId: '859862233087-qdagj10ar0mhv1i2ofljns6ilkq15r8o.apps.googleusercontent.com',
    iosClientId: '859862233087-th92vmu4n21q4bqcjfraurk6g4k3c5ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.doorSecurityLockApp.RunnerTests',
  );
}
